// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import product "github.com/my0sot1s/mpb/proto/xshop/product"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order_State int32

const (
	Order_PAID     Order_State = 0
	Order_OPEN     Order_State = 1
	Order_WAITTING Order_State = 2
	Order_REMOVE   Order_State = 3
)

var Order_State_name = map[int32]string{
	0: "PAID",
	1: "OPEN",
	2: "WAITTING",
	3: "REMOVE",
}
var Order_State_value = map[string]int32{
	"PAID":     0,
	"OPEN":     1,
	"WAITTING": 2,
	"REMOVE":   3,
}

func (x Order_State) String() string {
	return proto.EnumName(Order_State_name, int32(x))
}
func (Order_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{1, 0}
}

type Customer_State int32

const (
	Customer_PAID  Customer_State = 0
	Customer_NEWER Customer_State = 1
	Customer_BAN   Customer_State = 2
)

var Customer_State_name = map[int32]string{
	0: "PAID",
	1: "NEWER",
	2: "BAN",
}
var Customer_State_value = map[string]int32{
	"PAID":  0,
	"NEWER": 1,
	"BAN":   2,
}

func (x Customer_State) String() string {
	return proto.EnumName(Customer_State_name, int32(x))
}
func (Customer_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{2, 0}
}

type Invoice_State int32

const (
	Invoice_PAID Invoice_State = 0
	Invoice_VOID Invoice_State = 1
)

var Invoice_State_name = map[int32]string{
	0: "PAID",
	1: "VOID",
}
var Invoice_State_value = map[string]int32{
	"PAID": 0,
	"VOID": 1,
}

func (x Invoice_State) String() string {
	return proto.EnumName(Invoice_State_name, int32(x))
}
func (Invoice_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{4, 0}
}

type OrderItems struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductsId           []string             `protobuf:"bytes,2,rep,name=products_id,json=productsId,proto3" json:"products_id,omitempty"`
	Products             []*product.Product   `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	Quantity             int32                `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                int32                `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Discount             float32              `protobuf:"fixed32,6,opt,name=discount,proto3" json:"discount,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string               `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderItems) Reset()         { *m = OrderItems{} }
func (m *OrderItems) String() string { return proto.CompactTextString(m) }
func (*OrderItems) ProtoMessage()    {}
func (*OrderItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{0}
}
func (m *OrderItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItems.Unmarshal(m, b)
}
func (m *OrderItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItems.Marshal(b, m, deterministic)
}
func (dst *OrderItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItems.Merge(dst, src)
}
func (m *OrderItems) XXX_Size() int {
	return xxx_messageInfo_OrderItems.Size(m)
}
func (m *OrderItems) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItems.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItems proto.InternalMessageInfo

func (m *OrderItems) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderItems) GetProductsId() []string {
	if m != nil {
		return m.ProductsId
	}
	return nil
}

func (m *OrderItems) GetProducts() []*product.Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *OrderItems) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderItems) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderItems) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *OrderItems) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *OrderItems) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           []string             `protobuf:"bytes,2,rep,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Customer             []*Customer          `protobuf:"bytes,3,rep,name=customer,proto3" json:"customer,omitempty"`
	Price                int32                `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	OrderItems           *OrderItems          `protobuf:"bytes,5,opt,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	Discount             float32              `protobuf:"fixed32,6,opt,name=discount,proto3" json:"discount,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string               `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	State                Order_State          `protobuf:"varint,9,opt,name=state,proto3,enum=order.Order_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{1}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetCustomerId() []string {
	if m != nil {
		return m.CustomerId
	}
	return nil
}

func (m *Order) GetCustomer() []*Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Order) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetOrderItems() *OrderItems {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

func (m *Order) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Order) GetState() Order_State {
	if m != nil {
		return m.State
	}
	return Order_PAID
}

type Customer struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fullname             string               `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Phone                string               `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address              string               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	State                Customer_State       `protobuf:"varint,7,opt,name=state,proto3,enum=order.Customer_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{2}
}
func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (dst *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(dst, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *Customer) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Customer) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Customer) GetState() Customer_State {
	if m != nil {
		return m.State
	}
	return Customer_PAID
}

type PaymentMethod struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{3}
}
func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (dst *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(dst, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Invoice struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              string               `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Order                *Order               `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	CustomerId           string               `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Customer             *Customer            `protobuf:"bytes,5,opt,name=customer,proto3" json:"customer,omitempty"`
	Pm                   *PaymentMethod       `protobuf:"bytes,6,opt,name=pm,proto3" json:"pm,omitempty"`
	Note                 string               `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	Price                int32                `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	State                Invoice_State        `protobuf:"varint,9,opt,name=state,proto3,enum=order.Invoice_State" json:"state,omitempty"`
	RealPay              int32                `protobuf:"varint,12,opt,name=real_pay,json=realPay,proto3" json:"real_pay,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy            string               `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_a7bde40f7e782f4e, []int{4}
}
func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (dst *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(dst, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Invoice) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Invoice) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *Invoice) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Invoice) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *Invoice) GetPm() *PaymentMethod {
	if m != nil {
		return m.Pm
	}
	return nil
}

func (m *Invoice) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Invoice) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Invoice) GetState() Invoice_State {
	if m != nil {
		return m.State
	}
	return Invoice_PAID
}

func (m *Invoice) GetRealPay() int32 {
	if m != nil {
		return m.RealPay
	}
	return 0
}

func (m *Invoice) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Invoice) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderItems)(nil), "order.OrderItems")
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*Customer)(nil), "order.Customer")
	proto.RegisterType((*PaymentMethod)(nil), "order.PaymentMethod")
	proto.RegisterType((*Invoice)(nil), "order.Invoice")
	proto.RegisterEnum("order.Order_State", Order_State_name, Order_State_value)
	proto.RegisterEnum("order.Customer_State", Customer_State_name, Customer_State_value)
	proto.RegisterEnum("order.Invoice_State", Invoice_State_name, Invoice_State_value)
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_order_a7bde40f7e782f4e) }

var fileDescriptor_order_a7bde40f7e782f4e = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x49, 0xd2, 0x2c, 0xe9, 0xe9, 0x18, 0xc1, 0x1a, 0x52, 0x28, 0x42, 0xab, 0x22, 0x90,
	0x22, 0x86, 0x52, 0xe8, 0xe0, 0x62, 0x97, 0x1d, 0xab, 0x50, 0x2e, 0xd6, 0x56, 0x66, 0xda, 0x2e,
	0xab, 0xb4, 0xf6, 0xd6, 0x48, 0x4d, 0x1d, 0x12, 0x07, 0x91, 0x17, 0xd8, 0x0b, 0xf0, 0x2a, 0x3c,
	0x20, 0x8a, 0x1d, 0xf7, 0xdf, 0xc6, 0x2e, 0xb8, 0xe1, 0x2a, 0xfe, 0xec, 0xe3, 0x93, 0x7c, 0xbf,
	0x73, 0x4e, 0xa0, 0xc5, 0x32, 0x42, 0xb3, 0x20, 0xcd, 0x18, 0x67, 0xc8, 0x14, 0xa2, 0x7d, 0x7a,
	0x1b, 0xf3, 0x79, 0x31, 0x0d, 0x66, 0x2c, 0xe9, 0x26, 0xe5, 0x87, 0x9c, 0xf1, 0x8f, 0x79, 0x37,
	0x49, 0xa7, 0x5d, 0x11, 0xd5, 0xfd, 0x99, 0xcf, 0x59, 0x5a, 0xad, 0x49, 0x31, 0xe3, 0xea, 0x29,
	0x33, 0xb4, 0x8f, 0x6e, 0x19, 0xbb, 0x5d, 0x50, 0x19, 0x39, 0x2d, 0x6e, 0xba, 0x3c, 0x4e, 0x68,
	0xce, 0xa3, 0x24, 0x95, 0x01, 0xde, 0x2f, 0x1d, 0x60, 0x54, 0xbd, 0x25, 0xe4, 0x34, 0xc9, 0xd1,
	0x01, 0xe8, 0x31, 0x71, 0xb5, 0x8e, 0xe6, 0x37, 0xb1, 0x1e, 0x13, 0x74, 0x04, 0xad, 0x3a, 0x61,
	0x3e, 0x89, 0x89, 0xab, 0x77, 0x0c, 0xbf, 0x89, 0x41, 0x6d, 0x85, 0x04, 0xbd, 0x07, 0x5b, 0x29,
	0xd7, 0xe8, 0x18, 0x7e, 0xab, 0xe7, 0x04, 0xea, 0x13, 0xc6, 0xf2, 0x89, 0x57, 0x11, 0xa8, 0x0d,
	0xf6, 0xf7, 0x22, 0x5a, 0xf2, 0x98, 0x97, 0x6e, 0xa3, 0xa3, 0xf9, 0x26, 0x5e, 0x69, 0x74, 0x08,
	0x66, 0x9a, 0xc5, 0x33, 0xea, 0x9a, 0xe2, 0x40, 0x8a, 0xea, 0x06, 0x89, 0xf3, 0x19, 0x2b, 0x96,
	0xdc, 0xdd, 0xeb, 0x68, 0xbe, 0x8e, 0x57, 0x1a, 0x9d, 0x02, 0xcc, 0x32, 0x1a, 0x71, 0x4a, 0x26,
	0x11, 0x77, 0xad, 0x8e, 0xe6, 0xb7, 0x7a, 0xed, 0x40, 0x3a, 0x0e, 0x94, 0xe3, 0xe0, 0x52, 0x39,
	0xc6, 0xcd, 0x3a, 0xba, 0xcf, 0xd1, 0xeb, 0xf5, 0xd5, 0x69, 0xe9, 0xda, 0xc2, 0xaf, 0x3a, 0x3e,
	0x2b, 0xbd, 0x3b, 0x03, 0x4c, 0x41, 0xe5, 0x21, 0x20, 0xb3, 0x22, 0xe7, 0x2c, 0xa1, 0xd9, 0x06,
	0x10, 0xb5, 0x15, 0x12, 0x74, 0x0c, 0xb6, 0x52, 0x35, 0x90, 0x67, 0x81, 0xac, 0xe9, 0x97, 0x7a,
	0x1b, 0xaf, 0x02, 0xd6, 0x9e, 0x1b, 0x9b, 0x9e, 0x7b, 0x75, 0x17, 0x4c, 0xe2, 0xaa, 0x26, 0x82,
	0x47, 0xab, 0xf7, 0xbc, 0xce, 0xb2, 0x2e, 0x16, 0x06, 0xb6, 0x2e, 0xdc, 0x7f, 0xe1, 0x84, 0x7c,
	0x30, 0x73, 0x1e, 0x71, 0xea, 0x36, 0x3b, 0x9a, 0x7f, 0xd0, 0x43, 0x9b, 0xdf, 0x18, 0x7c, 0xab,
	0x4e, 0xb0, 0x0c, 0xf0, 0x3e, 0x83, 0x29, 0x34, 0xb2, 0xa1, 0x31, 0xee, 0x87, 0xe7, 0xce, 0x93,
	0x6a, 0x35, 0x1a, 0x0f, 0x86, 0x8e, 0x86, 0xf6, 0xc1, 0xbe, 0xee, 0x87, 0x97, 0x97, 0xe1, 0xf0,
	0xab, 0xa3, 0x23, 0x80, 0x3d, 0x3c, 0xb8, 0x18, 0x5d, 0x0d, 0x1c, 0xc3, 0xbb, 0xd3, 0xc1, 0x56,
	0xdc, 0xee, 0xd5, 0xa2, 0x0d, 0xf6, 0x4d, 0xb1, 0x58, 0x2c, 0xa3, 0x84, 0xba, 0xba, 0xd8, 0x5d,
	0x69, 0x41, 0x76, 0xce, 0x96, 0xd4, 0x35, 0xc4, 0x81, 0x14, 0xd5, 0x2e, 0x4d, 0xa2, 0x78, 0x21,
	0x78, 0x37, 0xb1, 0x14, 0xc8, 0x05, 0x2b, 0x22, 0x24, 0xa3, 0xb9, 0x64, 0xdd, 0xc4, 0x4a, 0xa2,
	0x4f, 0x60, 0xd5, 0x66, 0x05, 0xd4, 0xc7, 0xb1, 0xa9, 0x50, 0x74, 0xac, 0xa8, 0x58, 0x82, 0xca,
	0x8b, 0x9d, 0xfa, 0x6f, 0x83, 0x79, 0x7b, 0x1f, 0x4c, 0x13, 0xcc, 0xe1, 0xe0, 0x7a, 0x80, 0x1d,
	0x0d, 0x59, 0x60, 0x9c, 0xf5, 0x87, 0x8e, 0xee, 0x9d, 0xc0, 0xd3, 0x71, 0x54, 0x26, 0x74, 0xc9,
	0x2f, 0x28, 0x9f, 0x33, 0x72, 0x0f, 0x06, 0x82, 0xc6, 0x06, 0x08, 0xb1, 0xf6, 0x7e, 0x1b, 0x60,
	0x85, 0xcb, 0x1f, 0xac, 0x6a, 0xaa, 0xdd, 0xf8, 0x97, 0x60, 0xd7, 0x4d, 0x46, 0xea, 0x3b, 0x96,
	0x6c, 0x27, 0x82, 0x3c, 0x90, 0x3f, 0x1e, 0xc1, 0xae, 0xd5, 0xdb, 0xdf, 0xac, 0x2a, 0x96, 0x47,
	0xbb, 0x73, 0x20, 0x79, 0xfe, 0x6d, 0x0e, 0x64, 0x07, 0x3f, 0x32, 0x07, 0x6f, 0x40, 0x4f, 0x93,
	0x1a, 0xf1, 0x61, 0x1d, 0xb6, 0x65, 0x17, 0xeb, 0x69, 0x22, 0x2c, 0xb2, 0x1a, 0x6b, 0x65, 0x91,
	0x71, 0xba, 0x9e, 0x20, 0x7b, 0x73, 0x82, 0xde, 0x6d, 0xf7, 0xa5, 0x4a, 0x59, 0xb3, 0xd8, 0x2a,
	0x40, 0x05, 0x22, 0xa3, 0xd1, 0x62, 0x92, 0x46, 0xa5, 0xbb, 0x2f, 0x92, 0x58, 0x95, 0x1e, 0x47,
	0xe5, 0xce, 0xe0, 0xc0, 0xbf, 0x0f, 0x4e, 0x6b, 0xf7, 0x07, 0xf3, 0xea, 0xc1, 0x71, 0xb8, 0x1a,
	0x85, 0xe7, 0x8e, 0x36, 0xdd, 0x13, 0xa9, 0x4f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x66, 0x8b,
	0x7c, 0x51, 0x0c, 0x06, 0x00, 0x00,
}
