// Code generated by protoc-gen-go. DO NOT EDIT.
// source: campaign.proto

package campaign

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import product "github.com/my0sot1s/mpb/product"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Campaign struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventName            string           `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	Started              int32            `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	Ended                int32            `protobuf:"varint,4,opt,name=ended,proto3" json:"ended,omitempty"`
	Description          string           `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Image                []*product.Image `protobuf:"bytes,6,rep,name=image,proto3" json:"image,omitempty"`
	State                int32            `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_campaign_b8665faa7dadf27b, []int{0}
}
func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (dst *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(dst, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Campaign) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Campaign) GetStarted() int32 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Campaign) GetEnded() int32 {
	if m != nil {
		return m.Ended
	}
	return 0
}

func (m *Campaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Campaign) GetImage() []*product.Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Campaign) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*Campaign)(nil), "campaign.Campaign")
}

func init() { proto.RegisterFile("campaign.proto", fileDescriptor_campaign_b8665faa7dadf27b) }

var fileDescriptor_campaign_b8665faa7dadf27b = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x69, 0xd7, 0xae, 0xdd, 0x59, 0xe8, 0x21, 0x78, 0x18, 0x04, 0xa1, 0x88, 0x87, 0x5e,
	0x6c, 0xfd, 0x78, 0x04, 0x4f, 0x5e, 0x3c, 0xf4, 0x05, 0x24, 0x6d, 0x86, 0x9a, 0x43, 0x3e, 0x48,
	0x66, 0x05, 0x9f, 0xd0, 0xd7, 0x92, 0x4d, 0x0c, 0xec, 0x69, 0xf8, 0xfd, 0x86, 0xff, 0x9f, 0x19,
	0xe8, 0x56, 0x69, 0xbc, 0xd4, 0x9b, 0x1d, 0x7d, 0x70, 0xec, 0x44, 0x5b, 0xf8, 0xf6, 0x71, 0xd3,
	0xfc, 0x75, 0x5a, 0xc6, 0xd5, 0x99, 0xc9, 0xfc, 0x3c, 0x45, 0xc7, 0xcf, 0x71, 0x32, 0x7e, 0x99,
	0x7c, 0x70, 0xea, 0xb4, 0x72, 0x99, 0x39, 0x78, 0xff, 0x5b, 0x41, 0xfb, 0xf6, 0x9f, 0x15, 0x1d,
	0xd4, 0x5a, 0x61, 0xd5, 0x57, 0xc3, 0x61, 0xae, 0xb5, 0x12, 0x77, 0x00, 0xf4, 0x4d, 0x96, 0x3f,
	0xad, 0x34, 0x84, 0x75, 0xf2, 0x87, 0x64, 0x3e, 0xa4, 0x21, 0x81, 0x70, 0x1d, 0x59, 0x06, 0x26,
	0x85, 0xbb, 0xbe, 0x1a, 0x9a, 0xb9, 0xa0, 0xb8, 0x81, 0x86, 0xac, 0x22, 0x85, 0x57, 0xc9, 0x67,
	0x10, 0x3d, 0x1c, 0x15, 0xc5, 0x35, 0x68, 0xcf, 0xda, 0x59, 0x6c, 0x52, 0xdf, 0xa5, 0x12, 0x0f,
	0xd0, 0x68, 0x23, 0x37, 0xc2, 0x7d, 0xbf, 0x1b, 0x8e, 0x2f, 0xdd, 0x58, 0x8e, 0x7d, 0x3f, 0xdb,
	0x39, 0x2f, 0xcf, 0xed, 0x91, 0x25, 0x13, 0xb6, 0xb9, 0x3d, 0xc1, 0xb2, 0x4f, 0x0f, 0xbd, 0xfe,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xeb, 0x4a, 0x98, 0x1b, 0x01, 0x00, 0x00,
}
