// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Category_State int32

const (
	Category_ACTIVE         Category_State = 0
	Category_INACTIVE       Category_State = 1
	Category_OUT_OF_PRODUCT Category_State = 2
)

var Category_State_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "OUT_OF_PRODUCT",
}
var Category_State_value = map[string]int32{
	"ACTIVE":         0,
	"INACTIVE":       1,
	"OUT_OF_PRODUCT": 2,
}

func (x Category_State) String() string {
	return proto.EnumName(Category_State_name, int32(x))
}
func (Category_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{1, 0}
}

type Rate_State int32

const (
	Rate_ACTIVE   Rate_State = 0
	Rate_INACTIVE Rate_State = 1
)

var Rate_State_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
}
var Rate_State_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
}

func (x Rate_State) String() string {
	return proto.EnumName(Rate_State_name, int32(x))
}
func (Rate_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{3, 0}
}

type Tag_State int32

const (
	Tag_ACTIVE   Tag_State = 0
	Tag_INACTIVE Tag_State = 1
)

var Tag_State_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
}
var Tag_State_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
}

func (x Tag_State) String() string {
	return proto.EnumName(Tag_State_name, int32(x))
}
func (Tag_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{4, 0}
}

type Product_State int32

const (
	Product_ACTIVE   Product_State = 0
	Product_INACTIVE Product_State = 1
	Product_SOLD_OUT Product_State = 2
)

var Product_State_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "SOLD_OUT",
}
var Product_State_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
	"SOLD_OUT": 2,
}

func (x Product_State) String() string {
	return proto.EnumName(Product_State_name, int32(x))
}
func (Product_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{5, 0}
}

type Shipment_State int32

const (
	Shipment_ACTIVE   Shipment_State = 0
	Shipment_INACTIVE Shipment_State = 1
	Shipment_ENDED    Shipment_State = 2
)

var Shipment_State_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "ENDED",
}
var Shipment_State_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
	"ENDED":    2,
}

func (x Shipment_State) String() string {
	return proto.EnumName(Shipment_State_name, int32(x))
}
func (Shipment_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{6, 0}
}

type ShipmentItems_State int32

const (
	ShipmentItems_ACTIVE   ShipmentItems_State = 0
	ShipmentItems_INACTIVE ShipmentItems_State = 1
	ShipmentItems_ENDED    ShipmentItems_State = 2
)

var ShipmentItems_State_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "ENDED",
}
var ShipmentItems_State_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
	"ENDED":    2,
}

func (x ShipmentItems_State) String() string {
	return proto.EnumName(ShipmentItems_State_name, int32(x))
}
func (ShipmentItems_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{8, 0}
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{0}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Category struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Display              string               `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	State                Category_State       `protobuf:"varint,4,opt,name=state,proto3,enum=product.Category_State" json:"state,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{1}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Category) GetState() Category_State {
	if m != nil {
		return m.State
	}
	return Category_ACTIVE
}

func (m *Category) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type Group struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Display              string               `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Target               string               `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	BonusPrice           float32              `protobuf:"fixed32,6,opt,name=bonus_price,json=bonusPrice,proto3" json:"bonus_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{2}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Group) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Group) GetBonusPrice() float32 {
	if m != nil {
		return m.BonusPrice
	}
	return 0
}

type Rate struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	By                   string               `protobuf:"bytes,3,opt,name=by,proto3" json:"by,omitempty"`
	Score                float32              `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Rate) Reset()         { *m = Rate{} }
func (m *Rate) String() string { return proto.CompactTextString(m) }
func (*Rate) ProtoMessage()    {}
func (*Rate) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{3}
}
func (m *Rate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rate.Unmarshal(m, b)
}
func (m *Rate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rate.Marshal(b, m, deterministic)
}
func (dst *Rate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rate.Merge(dst, src)
}
func (m *Rate) XXX_Size() int {
	return xxx_messageInfo_Rate.Size(m)
}
func (m *Rate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rate.DiscardUnknown(m)
}

var xxx_messageInfo_Rate proto.InternalMessageInfo

func (m *Rate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Rate) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Rate) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

func (m *Rate) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Rate) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

type Tag struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Display              string    `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Notes                []string  `protobuf:"bytes,4,rep,name=notes,proto3" json:"notes,omitempty"`
	State                Tag_State `protobuf:"varint,5,opt,name=state,proto3,enum=product.Tag_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{4}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tag) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *Tag) GetNotes() []string {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *Tag) GetState() Tag_State {
	if m != nil {
		return m.State
	}
	return Tag_ACTIVE
}

type Product struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images               []*Image             `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	CategoriesId         []string             `protobuf:"bytes,6,rep,name=categories_id,json=categoriesId,proto3" json:"categories_id,omitempty"`
	Categories           []*Category          `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	GroupsId             []string             `protobuf:"bytes,8,rep,name=groups_id,json=groupsId,proto3" json:"groups_id,omitempty"`
	Groups               []*Group             `protobuf:"bytes,9,rep,name=groups,proto3" json:"groups,omitempty"`
	State                Product_State        `protobuf:"varint,10,opt,name=state,proto3,enum=product.Product_State" json:"state,omitempty"`
	ShipmentId           string               `protobuf:"bytes,11,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Shipment             *Shipment            `protobuf:"bytes,12,opt,name=shipment,proto3" json:"shipment,omitempty"`
	TagsId               []string             `protobuf:"bytes,13,rep,name=tags_id,json=tagsId,proto3" json:"tags_id,omitempty"`
	Tags                 []*Tag               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	Price                int32                `protobuf:"varint,15,opt,name=price,proto3" json:"price,omitempty"`
	AverageRate          float32              `protobuf:"fixed32,16,opt,name=average_rate,json=averageRate,proto3" json:"average_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{5}
}
func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (dst *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(dst, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Product) GetCategoriesId() []string {
	if m != nil {
		return m.CategoriesId
	}
	return nil
}

func (m *Product) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Product) GetGroupsId() []string {
	if m != nil {
		return m.GroupsId
	}
	return nil
}

func (m *Product) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Product) GetState() Product_State {
	if m != nil {
		return m.State
	}
	return Product_ACTIVE
}

func (m *Product) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *Product) GetShipment() *Shipment {
	if m != nil {
		return m.Shipment
	}
	return nil
}

func (m *Product) GetTagsId() []string {
	if m != nil {
		return m.TagsId
	}
	return nil
}

func (m *Product) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Product) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetAverageRate() float32 {
	if m != nil {
		return m.AverageRate
	}
	return 0
}

type Shipment struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notes                []string             `protobuf:"bytes,3,rep,name=notes,proto3" json:"notes,omitempty"`
	BasicInfo            string               `protobuf:"bytes,4,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	State                Shipment_State       `protobuf:"varint,6,opt,name=state,proto3,enum=product.Shipment_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Shipment) Reset()         { *m = Shipment{} }
func (m *Shipment) String() string { return proto.CompactTextString(m) }
func (*Shipment) ProtoMessage()    {}
func (*Shipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{6}
}
func (m *Shipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shipment.Unmarshal(m, b)
}
func (m *Shipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shipment.Marshal(b, m, deterministic)
}
func (dst *Shipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shipment.Merge(dst, src)
}
func (m *Shipment) XXX_Size() int {
	return xxx_messageInfo_Shipment.Size(m)
}
func (m *Shipment) XXX_DiscardUnknown() {
	xxx_messageInfo_Shipment.DiscardUnknown(m)
}

var xxx_messageInfo_Shipment proto.InternalMessageInfo

func (m *Shipment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shipment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Shipment) GetNotes() []string {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *Shipment) GetBasicInfo() string {
	if m != nil {
		return m.BasicInfo
	}
	return ""
}

func (m *Shipment) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Shipment) GetState() Shipment_State {
	if m != nil {
		return m.State
	}
	return Shipment_ACTIVE
}

type ShipmentProduct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Product              *Product `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice            int32    `protobuf:"varint,6,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Discount             float32  `protobuf:"fixed32,7,opt,name=discount,proto3" json:"discount,omitempty"`
	Note                 string   `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentProduct) Reset()         { *m = ShipmentProduct{} }
func (m *ShipmentProduct) String() string { return proto.CompactTextString(m) }
func (*ShipmentProduct) ProtoMessage()    {}
func (*ShipmentProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{7}
}
func (m *ShipmentProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentProduct.Unmarshal(m, b)
}
func (m *ShipmentProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentProduct.Marshal(b, m, deterministic)
}
func (dst *ShipmentProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentProduct.Merge(dst, src)
}
func (m *ShipmentProduct) XXX_Size() int {
	return xxx_messageInfo_ShipmentProduct.Size(m)
}
func (m *ShipmentProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentProduct.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentProduct proto.InternalMessageInfo

func (m *ShipmentProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShipmentProduct) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ShipmentProduct) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ShipmentProduct) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *ShipmentProduct) GetUnitPrice() int32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *ShipmentProduct) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *ShipmentProduct) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type ShipmentItems struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notes                []string             `protobuf:"bytes,3,rep,name=notes,proto3" json:"notes,omitempty"`
	ShipmentProduct      *ShipmentProduct     `protobuf:"bytes,4,opt,name=shipment_product,json=shipmentProduct,proto3" json:"shipment_product,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	Price                int32                `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Discount             float32              `protobuf:"fixed32,8,opt,name=discount,proto3" json:"discount,omitempty"`
	State                ShipmentItems_State  `protobuf:"varint,6,opt,name=state,proto3,enum=product.ShipmentItems_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ShipmentItems) Reset()         { *m = ShipmentItems{} }
func (m *ShipmentItems) String() string { return proto.CompactTextString(m) }
func (*ShipmentItems) ProtoMessage()    {}
func (*ShipmentItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_f7ba2c5646a54398, []int{8}
}
func (m *ShipmentItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentItems.Unmarshal(m, b)
}
func (m *ShipmentItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentItems.Marshal(b, m, deterministic)
}
func (dst *ShipmentItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentItems.Merge(dst, src)
}
func (m *ShipmentItems) XXX_Size() int {
	return xxx_messageInfo_ShipmentItems.Size(m)
}
func (m *ShipmentItems) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentItems.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentItems proto.InternalMessageInfo

func (m *ShipmentItems) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShipmentItems) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShipmentItems) GetNotes() []string {
	if m != nil {
		return m.Notes
	}
	return nil
}

func (m *ShipmentItems) GetShipmentProduct() *ShipmentProduct {
	if m != nil {
		return m.ShipmentProduct
	}
	return nil
}

func (m *ShipmentItems) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *ShipmentItems) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ShipmentItems) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *ShipmentItems) GetState() ShipmentItems_State {
	if m != nil {
		return m.State
	}
	return ShipmentItems_ACTIVE
}

func init() {
	proto.RegisterType((*Image)(nil), "product.Image")
	proto.RegisterType((*Category)(nil), "product.Category")
	proto.RegisterType((*Group)(nil), "product.Group")
	proto.RegisterType((*Rate)(nil), "product.Rate")
	proto.RegisterType((*Tag)(nil), "product.Tag")
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Shipment)(nil), "product.Shipment")
	proto.RegisterType((*ShipmentProduct)(nil), "product.ShipmentProduct")
	proto.RegisterType((*ShipmentItems)(nil), "product.ShipmentItems")
	proto.RegisterEnum("product.Category_State", Category_State_name, Category_State_value)
	proto.RegisterEnum("product.Rate_State", Rate_State_name, Rate_State_value)
	proto.RegisterEnum("product.Tag_State", Tag_State_name, Tag_State_value)
	proto.RegisterEnum("product.Product_State", Product_State_name, Product_State_value)
	proto.RegisterEnum("product.Shipment_State", Shipment_State_name, Shipment_State_value)
	proto.RegisterEnum("product.ShipmentItems_State", ShipmentItems_State_name, ShipmentItems_State_value)
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_product_f7ba2c5646a54398) }

var fileDescriptor_product_f7ba2c5646a54398 = []byte{
	// 860 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xe1, 0x6e, 0xe3, 0x44,
	0x10, 0xc6, 0x4e, 0xec, 0xd8, 0x93, 0x34, 0x0d, 0xab, 0x53, 0xcf, 0x2a, 0x9c, 0x9a, 0x33, 0x12,
	0x8a, 0xd0, 0x5d, 0x2a, 0x02, 0x3c, 0x00, 0x6a, 0x0b, 0xb2, 0x84, 0x2e, 0xd5, 0x36, 0x85, 0x9f,
	0x91, 0x13, 0x6f, 0xdd, 0x95, 0x1a, 0x6f, 0xf0, 0x6e, 0x40, 0x79, 0x0d, 0x5e, 0x84, 0x77, 0xe0,
	0x25, 0xe0, 0x25, 0xf8, 0xc3, 0x0f, 0x7e, 0xa3, 0x1d, 0xef, 0xba, 0x69, 0x02, 0x6a, 0x49, 0xef,
	0xdf, 0xce, 0xec, 0x78, 0x67, 0xbe, 0x99, 0xef, 0x1b, 0xc3, 0xc1, 0xb2, 0x14, 0xd9, 0x6a, 0xae,
	0x86, 0xcb, 0x52, 0x28, 0x41, 0x5a, 0xc6, 0x3c, 0x3e, 0xc9, 0x85, 0xc8, 0xef, 0xd8, 0x29, 0xba,
	0x67, 0xab, 0x9b, 0x53, 0xc5, 0x17, 0x4c, 0xaa, 0x74, 0xb1, 0xac, 0x22, 0xe3, 0x1f, 0xc0, 0x4b,
	0x16, 0x69, 0xce, 0x48, 0x17, 0x5c, 0x9e, 0x45, 0x4e, 0xdf, 0x19, 0x84, 0xd4, 0xe5, 0x19, 0xe9,
	0x41, 0x63, 0x55, 0xde, 0x45, 0x2e, 0x3a, 0xf4, 0x91, 0xbc, 0x00, 0xef, 0x67, 0x9e, 0xa9, 0xdb,
	0xa8, 0xd1, 0x77, 0x06, 0x1e, 0xad, 0x0c, 0x72, 0x04, 0xfe, 0x2d, 0xe3, 0xf9, 0xad, 0x8a, 0x9a,
	0xe8, 0x36, 0x56, 0xfc, 0x97, 0x03, 0xc1, 0x59, 0xaa, 0x58, 0x2e, 0xca, 0xf5, 0xce, 0xe3, 0x11,
	0xb4, 0x32, 0x2e, 0x97, 0x77, 0xe9, 0xda, 0x24, 0xb0, 0x26, 0xe9, 0x43, 0x3b, 0x63, 0x72, 0x5e,
	0xf2, 0xa5, 0xe2, 0xa2, 0xc0, 0x54, 0x21, 0xdd, 0x74, 0x91, 0xb7, 0xe0, 0x49, 0x95, 0x2a, 0x86,
	0xf9, 0xba, 0xa3, 0x97, 0x43, 0x0b, 0xdd, 0x66, 0x1b, 0x5e, 0xe9, 0x6b, 0x5a, 0x45, 0x91, 0x2f,
	0xa1, 0x35, 0x2f, 0x59, 0xaa, 0x58, 0x16, 0x79, 0x7d, 0x67, 0xd0, 0x1e, 0x1d, 0x0f, 0xab, 0x9e,
	0x0c, 0x6d, 0x4f, 0x86, 0x13, 0xdb, 0x13, 0x6a, 0x43, 0xe3, 0xaf, 0xc0, 0xc3, 0x57, 0x08, 0x80,
	0xff, 0xf5, 0xd9, 0x24, 0xf9, 0xfe, 0xa2, 0xf7, 0x01, 0xe9, 0x40, 0x90, 0xbc, 0x33, 0x96, 0x43,
	0x08, 0x74, 0xc7, 0xd7, 0x93, 0xe9, 0xf8, 0x9b, 0xe9, 0x25, 0x1d, 0x9f, 0x5f, 0x9f, 0x4d, 0x7a,
	0x6e, 0xfc, 0x9b, 0x03, 0xde, 0xb7, 0xa5, 0x58, 0x2d, 0xdf, 0x2b, 0xe2, 0x23, 0xf0, 0x55, 0x5a,
	0xe6, 0xac, 0x6a, 0x71, 0x48, 0x8d, 0xb5, 0x1f, 0x34, 0x72, 0x02, 0xed, 0x99, 0x28, 0x56, 0x72,
	0xba, 0x2c, 0xf9, 0x9c, 0x45, 0x7e, 0xdf, 0x19, 0xb8, 0x14, 0xd0, 0x75, 0xa9, 0x3d, 0xf1, 0xaf,
	0x0e, 0x34, 0xa9, 0xc6, 0xfe, 0x2f, 0x18, 0x16, 0x4c, 0xca, 0x34, 0x67, 0x16, 0x83, 0x31, 0x75,
	0xe4, 0x6c, 0x6d, 0x4a, 0x77, 0x67, 0x6b, 0x4d, 0x15, 0x39, 0x17, 0x25, 0xc3, 0xba, 0x5c, 0x5a,
	0x19, 0x9b, 0xf5, 0xfa, 0x4f, 0x1f, 0xc5, 0xeb, 0x47, 0x47, 0x11, 0xff, 0xe2, 0x40, 0x63, 0x92,
	0xe6, 0xff, 0xa3, 0xe9, 0x2f, 0xc0, 0x2b, 0x84, 0x62, 0x32, 0x6a, 0xf6, 0x1b, 0x83, 0x90, 0x56,
	0x06, 0x19, 0x58, 0x6a, 0x79, 0x48, 0x2d, 0x52, 0x53, 0x6b, 0x92, 0xe6, 0x0f, 0x58, 0xf5, 0x94,
	0xa2, 0xfe, 0x6c, 0x42, 0xeb, 0xb2, 0xfa, 0x7e, 0xa7, 0x30, 0x02, 0xcd, 0x22, 0x5d, 0xd8, 0x36,
	0xe2, 0x99, 0x7c, 0x0a, 0x3e, 0xd7, 0x4a, 0x94, 0x51, 0xa3, 0xdf, 0x18, 0xb4, 0x47, 0xdd, 0x3a,
	0x3b, 0x0a, 0x94, 0x9a, 0xdb, 0x6d, 0xbe, 0x34, 0x77, 0xf9, 0xb2, 0x1f, 0x2f, 0x3e, 0x81, 0x83,
	0x79, 0xa5, 0x20, 0xce, 0xe4, 0x94, 0xeb, 0x19, 0xe9, 0xd6, 0x74, 0xee, 0x9d, 0x49, 0x46, 0x3e,
	0x07, 0xb8, 0xb7, 0xa3, 0x16, 0x16, 0xfa, 0xe1, 0x8e, 0x02, 0xe9, 0x46, 0x10, 0xf9, 0x08, 0xc2,
	0x5c, 0x4b, 0x02, 0xdf, 0x0c, 0xf0, 0xcd, 0xa0, 0x72, 0x24, 0x99, 0x06, 0x5d, 0x9d, 0xa3, 0x70,
	0x0b, 0x34, 0xca, 0x88, 0x9a, 0x5b, 0xf2, 0xc6, 0x4e, 0x06, 0x70, 0x32, 0x47, 0x75, 0x98, 0xe9,
	0xf0, 0x43, 0xcd, 0x9f, 0x40, 0x5b, 0xde, 0xf2, 0xe5, 0x82, 0x15, 0x4a, 0x27, 0x6d, 0x63, 0x8b,
	0xc0, 0xba, 0x92, 0x8c, 0xbc, 0x85, 0xc0, 0x5a, 0x51, 0x07, 0x5b, 0x74, 0x0f, 0xe2, 0xca, 0x5c,
	0xd0, 0x3a, 0x84, 0xbc, 0x84, 0x96, 0x4a, 0x73, 0x04, 0x70, 0x80, 0x00, 0x7c, 0x6d, 0x26, 0x19,
	0xe9, 0x43, 0x53, 0x9f, 0xa2, 0x2e, 0x16, 0xdf, 0xd9, 0xe4, 0x0b, 0xc5, 0x1b, 0x4d, 0xb4, 0x4a,
	0x67, 0x87, 0xd5, 0xd2, 0x44, 0x83, 0xbc, 0x86, 0x4e, 0xfa, 0x13, 0x2b, 0xd3, 0x9c, 0x4d, 0x4b,
	0x8d, 0xaa, 0x87, 0x32, 0x69, 0x1b, 0x9f, 0x16, 0x5f, 0x7c, 0xfa, 0xf8, 0x06, 0xea, 0x40, 0x70,
	0x35, 0xfe, 0xee, 0x7c, 0x3a, 0xbe, 0xd6, 0xbb, 0xe7, 0x6f, 0x07, 0x02, 0x5b, 0xfb, 0x93, 0x08,
	0x57, 0x6b, 0xa0, 0xb1, 0xa9, 0x81, 0x57, 0x00, 0xb3, 0x54, 0xf2, 0xf9, 0x94, 0x17, 0x37, 0xc2,
	0xb0, 0x2b, 0x44, 0x4f, 0x52, 0xdc, 0x88, 0x3d, 0xb9, 0x55, 0xef, 0x6c, 0x7f, 0x6b, 0x67, 0xdb,
	0x82, 0x1f, 0xaa, 0xeb, 0xcd, 0xe3, 0xd8, 0x43, 0xf0, 0x2e, 0xde, 0x9d, 0x5f, 0x9c, 0xf7, 0xdc,
	0xf8, 0x77, 0x07, 0x0e, 0xed, 0x3b, 0xff, 0x25, 0xb8, 0x57, 0x00, 0x26, 0xa5, 0x1e, 0x62, 0xd5,
	0x85, 0xd0, 0x78, 0x92, 0x8c, 0x7c, 0x06, 0xf6, 0x8f, 0x89, 0x4b, 0xac, 0x3d, 0xea, 0x6d, 0x13,
	0x8c, 0xda, 0x00, 0x72, 0x0c, 0xc1, 0x8f, 0xab, 0xb4, 0x50, 0x5c, 0xad, 0xcd, 0x2f, 0xaf, 0xb6,
	0x75, 0x9a, 0x55, 0xc1, 0xd5, 0xc6, 0x6a, 0xf5, 0x68, 0xa8, 0x3d, 0xb8, 0x59, 0xf5, 0xa7, 0x19,
	0x97, 0x73, 0xb1, 0x2a, 0x54, 0xd4, 0xc2, 0x91, 0xd7, 0x36, 0x4e, 0x48, 0x98, 0xd5, 0xa3, 0x27,
	0x24, 0x14, 0x8b, 0xff, 0x70, 0xe1, 0xc0, 0x22, 0x4b, 0x14, 0x5b, 0xc8, 0x67, 0xcc, 0xf5, 0x0c,
	0x7a, 0xb5, 0x26, 0x2c, 0xd6, 0x26, 0x62, 0x8d, 0x76, 0xa6, 0x61, 0x31, 0x1f, 0xca, 0xad, 0xb6,
	0xee, 0x37, 0xfd, 0x5a, 0x03, 0xad, 0x4d, 0x0d, 0x6c, 0x36, 0x23, 0xd8, 0x6a, 0xc6, 0xe8, 0x21,
	0x5f, 0x3e, 0xde, 0xa9, 0x10, 0xbb, 0xf1, 0x0c, 0xd2, 0xcc, 0x7c, 0x2c, 0xf8, 0x8b, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x51, 0xe1, 0xca, 0x8c, 0x39, 0x09, 0x00, 0x00,
}
