// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reqres.proto

package reqres

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqQuery struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Anchor               string   `protobuf:"bytes,3,opt,name=anchor,proto3" json:"anchor,omitempty"`
	OrderBy              string   `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqQuery) Reset()         { *m = ReqQuery{} }
func (m *ReqQuery) String() string { return proto.CompactTextString(m) }
func (*ReqQuery) ProtoMessage()    {}
func (*ReqQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_reqres_bec8e7046e80d869, []int{0}
}
func (m *ReqQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqQuery.Unmarshal(m, b)
}
func (m *ReqQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqQuery.Marshal(b, m, deterministic)
}
func (dst *ReqQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqQuery.Merge(dst, src)
}
func (m *ReqQuery) XXX_Size() int {
	return xxx_messageInfo_ReqQuery.Size(m)
}
func (m *ReqQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ReqQuery proto.InternalMessageInfo

func (m *ReqQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReqQuery) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReqQuery) GetAnchor() string {
	if m != nil {
		return m.Anchor
	}
	return ""
}

func (m *ReqQuery) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type ReqId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqId) Reset()         { *m = ReqId{} }
func (m *ReqId) String() string { return proto.CompactTextString(m) }
func (*ReqId) ProtoMessage()    {}
func (*ReqId) Descriptor() ([]byte, []int) {
	return fileDescriptor_reqres_bec8e7046e80d869, []int{1}
}
func (m *ReqId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqId.Unmarshal(m, b)
}
func (m *ReqId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqId.Marshal(b, m, deterministic)
}
func (dst *ReqId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqId.Merge(dst, src)
}
func (m *ReqId) XXX_Size() int {
	return xxx_messageInfo_ReqId.Size(m)
}
func (m *ReqId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqId proto.InternalMessageInfo

func (m *ReqId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqQuery)(nil), "reqres.ReqQuery")
	proto.RegisterType((*ReqId)(nil), "reqres.ReqId")
}

func init() { proto.RegisterFile("reqres.proto", fileDescriptor_reqres_bec8e7046e80d869) }

var fileDescriptor_reqres_bec8e7046e80d869 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x2d, 0x2c,
	0x4a, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x92, 0xb9, 0x38,
	0x82, 0x52, 0x0b, 0x03, 0x4b, 0x53, 0x8b, 0x2a, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x73, 0x32, 0x73, 0x33,
	0x4b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x21, 0x31, 0x2e, 0xb6, 0xc4, 0xbc,
	0xe4, 0x8c, 0xfc, 0x22, 0x09, 0x66, 0xb0, 0x4a, 0x28, 0x4f, 0x48, 0x92, 0x8b, 0x23, 0xbf, 0x28,
	0x25, 0xb5, 0x28, 0x3e, 0xa9, 0x52, 0x82, 0x05, 0x2c, 0xc3, 0x0e, 0xe6, 0x3b, 0x55, 0x2a, 0x89,
	0x73, 0xb1, 0x06, 0xa5, 0x16, 0x7a, 0xa6, 0xa0, 0xdb, 0x90, 0xc4, 0x06, 0x76, 0x8c, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x21, 0xa1, 0xb1, 0x6b, 0x9c, 0x00, 0x00, 0x00,
}
