// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cart.proto

package mpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CustomeInfo_State int32

const (
	CustomeInfo_BAN      CustomeInfo_State = 0
	CustomeInfo_PAID     CustomeInfo_State = 1
	CustomeInfo_CANCELED CustomeInfo_State = 2
)

var CustomeInfo_State_name = map[int32]string{
	0: "BAN",
	1: "PAID",
	2: "CANCELED",
}
var CustomeInfo_State_value = map[string]int32{
	"BAN":      0,
	"PAID":     1,
	"CANCELED": 2,
}

func (x CustomeInfo_State) String() string {
	return proto.EnumName(CustomeInfo_State_name, int32(x))
}
func (CustomeInfo_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{0, 0}
}

type Cart_State int32

const (
	Cart_PAID   Cart_State = 0
	Cart_UNPAID Cart_State = 1
	Cart_DELETE Cart_State = 2
	Cart_VOID   Cart_State = 3
)

var Cart_State_name = map[int32]string{
	0: "PAID",
	1: "UNPAID",
	2: "DELETE",
	3: "VOID",
}
var Cart_State_value = map[string]int32{
	"PAID":   0,
	"UNPAID": 1,
	"DELETE": 2,
	"VOID":   3,
}

func (x Cart_State) String() string {
	return proto.EnumName(Cart_State_name, int32(x))
}
func (Cart_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{2, 0}
}

type Bill_PayWith int32

const (
	Bill_BANK_TRANFER Bill_PayWith = 0
	Bill_DEFAULT      Bill_PayWith = 1
	Bill_CREDIT       Bill_PayWith = 2
)

var Bill_PayWith_name = map[int32]string{
	0: "BANK_TRANFER",
	1: "DEFAULT",
	2: "CREDIT",
}
var Bill_PayWith_value = map[string]int32{
	"BANK_TRANFER": 0,
	"DEFAULT":      1,
	"CREDIT":       2,
}

func (x Bill_PayWith) String() string {
	return proto.EnumName(Bill_PayWith_name, int32(x))
}
func (Bill_PayWith) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{3, 0}
}

type Bill_State int32

const (
	Bill_PAID   Bill_State = 0
	Bill_UNPAID Bill_State = 1
	Bill_DELETE Bill_State = 2
	Bill_VOID   Bill_State = 3
)

var Bill_State_name = map[int32]string{
	0: "PAID",
	1: "UNPAID",
	2: "DELETE",
	3: "VOID",
}
var Bill_State_value = map[string]int32{
	"PAID":   0,
	"UNPAID": 1,
	"DELETE": 2,
	"VOID":   3,
}

func (x Bill_State) String() string {
	return proto.EnumName(Bill_State_name, int32(x))
}
func (Bill_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{3, 1}
}

type CustomeInfo struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string               `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string               `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Address              string               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	State                CustomeInfo_State    `protobuf:"varint,6,opt,name=state,proto3,enum=mpb.CustomeInfo_State" json:"state,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Score                int32                `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	Paid                 int32                `protobuf:"varint,9,opt,name=paid,proto3" json:"paid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CustomeInfo) Reset()         { *m = CustomeInfo{} }
func (m *CustomeInfo) String() string { return proto.CompactTextString(m) }
func (*CustomeInfo) ProtoMessage()    {}
func (*CustomeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{0}
}
func (m *CustomeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomeInfo.Unmarshal(m, b)
}
func (m *CustomeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomeInfo.Marshal(b, m, deterministic)
}
func (dst *CustomeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomeInfo.Merge(dst, src)
}
func (m *CustomeInfo) XXX_Size() int {
	return xxx_messageInfo_CustomeInfo.Size(m)
}
func (m *CustomeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CustomeInfo proto.InternalMessageInfo

func (m *CustomeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CustomeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomeInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomeInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomeInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CustomeInfo) GetState() CustomeInfo_State {
	if m != nil {
		return m.State
	}
	return CustomeInfo_BAN
}

func (m *CustomeInfo) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *CustomeInfo) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *CustomeInfo) GetPaid() int32 {
	if m != nil {
		return m.Paid
	}
	return 0
}

type ProductSold struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Product              *Product `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	PriceSold            int32    `protobuf:"varint,2,opt,name=price_sold,json=priceSold,proto3" json:"price_sold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSold) Reset()         { *m = ProductSold{} }
func (m *ProductSold) String() string { return proto.CompactTextString(m) }
func (*ProductSold) ProtoMessage()    {}
func (*ProductSold) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{1}
}
func (m *ProductSold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSold.Unmarshal(m, b)
}
func (m *ProductSold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSold.Marshal(b, m, deterministic)
}
func (dst *ProductSold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSold.Merge(dst, src)
}
func (m *ProductSold) XXX_Size() int {
	return xxx_messageInfo_ProductSold.Size(m)
}
func (m *ProductSold) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSold.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSold proto.InternalMessageInfo

func (m *ProductSold) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProductSold) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProductSold) GetPriceSold() int32 {
	if m != nil {
		return m.PriceSold
	}
	return 0
}

type Cart struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalPrice           int32                `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	AllDiscount          float32              `protobuf:"fixed32,4,opt,name=all_discount,json=allDiscount,proto3" json:"all_discount,omitempty"`
	Note                 []string             `protobuf:"bytes,3,rep,name=note,proto3" json:"note,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created,proto3" json:"created,omitempty"`
	State                Cart_State           `protobuf:"varint,6,opt,name=state,proto3,enum=mpb.Cart_State" json:"state,omitempty"`
	Customer             *CustomeInfo         `protobuf:"bytes,7,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{2}
}
func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (dst *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(dst, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cart) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Cart) GetAllDiscount() float32 {
	if m != nil {
		return m.AllDiscount
	}
	return 0
}

func (m *Cart) GetNote() []string {
	if m != nil {
		return m.Note
	}
	return nil
}

func (m *Cart) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Cart) GetState() Cart_State {
	if m != nil {
		return m.State
	}
	return Cart_PAID
}

func (m *Cart) GetCustomer() *CustomeInfo {
	if m != nil {
		return m.Customer
	}
	return nil
}

type Bill struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalPrice           int32                `protobuf:"varint,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	State                Bill_State           `protobuf:"varint,4,opt,name=state,proto3,enum=mpb.Bill_State" json:"state,omitempty"`
	PayWith              Bill_PayWith         `protobuf:"varint,5,opt,name=pay_with,json=payWith,proto3,enum=mpb.Bill_PayWith" json:"pay_with,omitempty"`
	RealPay              int32                `protobuf:"varint,6,opt,name=real_pay,json=realPay,proto3" json:"real_pay,omitempty"`
	CustomerName         string               `protobuf:"bytes,7,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CardId               string               `protobuf:"bytes,8,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Bill) Reset()         { *m = Bill{} }
func (m *Bill) String() string { return proto.CompactTextString(m) }
func (*Bill) ProtoMessage()    {}
func (*Bill) Descriptor() ([]byte, []int) {
	return fileDescriptor_cart_a2ca4cf8c9d39251, []int{3}
}
func (m *Bill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bill.Unmarshal(m, b)
}
func (m *Bill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bill.Marshal(b, m, deterministic)
}
func (dst *Bill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bill.Merge(dst, src)
}
func (m *Bill) XXX_Size() int {
	return xxx_messageInfo_Bill.Size(m)
}
func (m *Bill) XXX_DiscardUnknown() {
	xxx_messageInfo_Bill.DiscardUnknown(m)
}

var xxx_messageInfo_Bill proto.InternalMessageInfo

func (m *Bill) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bill) GetTotalPrice() int32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Bill) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Bill) GetState() Bill_State {
	if m != nil {
		return m.State
	}
	return Bill_PAID
}

func (m *Bill) GetPayWith() Bill_PayWith {
	if m != nil {
		return m.PayWith
	}
	return Bill_BANK_TRANFER
}

func (m *Bill) GetRealPay() int32 {
	if m != nil {
		return m.RealPay
	}
	return 0
}

func (m *Bill) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Bill) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomeInfo)(nil), "mpb.CustomeInfo")
	proto.RegisterType((*ProductSold)(nil), "mpb.ProductSold")
	proto.RegisterType((*Cart)(nil), "mpb.Cart")
	proto.RegisterType((*Bill)(nil), "mpb.Bill")
	proto.RegisterEnum("mpb.CustomeInfo_State", CustomeInfo_State_name, CustomeInfo_State_value)
	proto.RegisterEnum("mpb.Cart_State", Cart_State_name, Cart_State_value)
	proto.RegisterEnum("mpb.Bill_PayWith", Bill_PayWith_name, Bill_PayWith_value)
	proto.RegisterEnum("mpb.Bill_State", Bill_State_name, Bill_State_value)
}

func init() { proto.RegisterFile("cart.proto", fileDescriptor_cart_a2ca4cf8c9d39251) }

var fileDescriptor_cart_a2ca4cf8c9d39251 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xd1, 0x6e, 0x9b, 0x3e,
	0x14, 0xc6, 0x1b, 0x08, 0x21, 0x39, 0xa4, 0xfd, 0xf3, 0xb7, 0xa6, 0x8d, 0x55, 0x9a, 0x9a, 0x31,
	0x6d, 0xca, 0x45, 0x45, 0xa5, 0xb4, 0x2f, 0x90, 0x06, 0x2a, 0x45, 0xab, 0xb2, 0xc8, 0x4d, 0xb7,
	0x4b, 0xe4, 0x60, 0xb7, 0x45, 0x82, 0x18, 0x81, 0xa3, 0x29, 0x2f, 0xb0, 0xc7, 0xd9, 0x5e, 0x71,
	0xf2, 0x01, 0xb6, 0x76, 0xb9, 0xd9, 0x7a, 0xe7, 0xf3, 0x71, 0x8c, 0xcf, 0xf7, 0xfd, 0x6c, 0x80,
	0x84, 0x95, 0x2a, 0x28, 0x4a, 0xa9, 0x24, 0x31, 0xf3, 0x62, 0x7d, 0x7c, 0x72, 0x2f, 0xe5, 0x7d,
	0x26, 0xce, 0x50, 0x5a, 0x6f, 0xef, 0xce, 0x54, 0x9a, 0x8b, 0x4a, 0xb1, 0xbc, 0xa8, 0xbb, 0x8e,
	0x0f, 0x8b, 0x52, 0xf2, 0x6d, 0xd2, 0x6c, 0xf2, 0x7f, 0x18, 0xe0, 0xcc, 0xb6, 0x95, 0x92, 0xb9,
	0x98, 0x6f, 0xee, 0x24, 0x39, 0x02, 0x23, 0xe5, 0x5e, 0x67, 0xd4, 0x19, 0x0f, 0xa8, 0x91, 0x72,
	0x42, 0xa0, 0xbb, 0x61, 0xb9, 0xf0, 0x0c, 0x54, 0x70, 0x4d, 0x5e, 0x80, 0x55, 0x3c, 0xc8, 0x8d,
	0xf0, 0x4c, 0x14, 0xeb, 0x42, 0xab, 0x22, 0x67, 0x69, 0xe6, 0x75, 0x6b, 0x15, 0x0b, 0xe2, 0x81,
	0xcd, 0x38, 0x2f, 0x45, 0x55, 0x79, 0x16, 0xea, 0x6d, 0x49, 0x4e, 0xc1, 0xaa, 0x14, 0x53, 0xc2,
	0xeb, 0x8d, 0x3a, 0xe3, 0xa3, 0xc9, 0xcb, 0x20, 0x2f, 0xd6, 0xc1, 0xa3, 0x51, 0x82, 0x1b, 0xfd,
	0x95, 0xd6, 0x4d, 0xe4, 0x02, 0xec, 0xa4, 0x14, 0x4c, 0x09, 0xee, 0xd9, 0xa3, 0xce, 0xd8, 0x99,
	0x1c, 0x07, 0xb5, 0xd3, 0xa0, 0x75, 0x1a, 0xac, 0x5a, 0xa7, 0xb4, 0x6d, 0xd5, 0x33, 0x55, 0x89,
	0x2c, 0x85, 0xd7, 0x1f, 0x75, 0xc6, 0x16, 0xad, 0x0b, 0xed, 0xa9, 0x60, 0x29, 0xf7, 0x06, 0x28,
	0xe2, 0xda, 0x1f, 0x83, 0x85, 0xe7, 0x11, 0x1b, 0xcc, 0xcb, 0xe9, 0xc2, 0x3d, 0x20, 0x7d, 0xe8,
	0x2e, 0xa7, 0xf3, 0xd0, 0xed, 0x90, 0x21, 0xf4, 0x67, 0xd3, 0xc5, 0x2c, 0xba, 0x8e, 0x42, 0xd7,
	0xf0, 0x39, 0x38, 0xcb, 0x3a, 0xc2, 0x1b, 0x99, 0xf1, 0xbd, 0xc0, 0x3e, 0x80, 0xdd, 0x24, 0x8c,
	0xf1, 0x38, 0x93, 0x21, 0x1a, 0x6b, 0xb6, 0xd0, 0xf6, 0x23, 0x79, 0x03, 0x50, 0x94, 0x69, 0x22,
	0xe2, 0x4a, 0x66, 0x1c, 0xe3, 0xb5, 0xe8, 0x00, 0x15, 0xfd, 0x5b, 0xff, 0xbb, 0x01, 0xdd, 0x19,
	0x2b, 0xd5, 0xde, 0xff, 0x4f, 0xc0, 0x51, 0x52, 0xb1, 0x2c, 0xc6, 0xde, 0x66, 0x23, 0xa0, 0xb4,
	0xd4, 0x0a, 0x79, 0x0b, 0x43, 0x96, 0x65, 0x31, 0x4f, 0xab, 0x44, 0x6e, 0x37, 0x0a, 0x71, 0x18,
	0xd4, 0x61, 0x59, 0x16, 0x36, 0x12, 0x42, 0x95, 0x4a, 0xf3, 0x33, 0x11, 0xaa, 0x7c, 0x1a, 0xb0,
	0xf5, 0xf7, 0x01, 0xbf, 0x7f, 0x0a, 0xf1, 0xbf, 0x1a, 0xa2, 0xbe, 0x93, 0x4f, 0xe8, 0x9d, 0x42,
	0x3f, 0xa9, 0xc9, 0x96, 0x0d, 0x3e, 0xf7, 0x4f, 0xdc, 0xf4, 0x57, 0x87, 0x7f, 0xde, 0xb2, 0x68,
	0x11, 0x1c, 0x10, 0x80, 0xde, 0xed, 0xa2, 0xc1, 0x01, 0xd0, 0x0b, 0xa3, 0xeb, 0x68, 0x15, 0xb9,
	0x86, 0xee, 0xf8, 0xfc, 0x69, 0x1e, 0xba, 0xa6, 0xff, 0xcd, 0x84, 0xee, 0x65, 0x9a, 0x65, 0xff,
	0x1e, 0xd8, 0x23, 0xe7, 0xe6, 0x33, 0x9c, 0x77, 0x1f, 0x39, 0xd7, 0x03, 0xec, 0x39, 0x2f, 0xd8,
	0x2e, 0xfe, 0x9a, 0xaa, 0x07, 0xcc, 0xf5, 0x68, 0xf2, 0xff, 0xef, 0xce, 0x25, 0xdb, 0x7d, 0x49,
	0xd5, 0x03, 0xb5, 0x8b, 0x7a, 0x41, 0x5e, 0x43, 0xbf, 0x14, 0x7a, 0x54, 0xb6, 0xc3, 0x44, 0x2d,
	0x6a, 0xeb, 0x7a, 0xc9, 0x76, 0xe4, 0x1d, 0x1c, 0xb6, 0x01, 0xc5, 0xf8, 0x22, 0x6d, 0x74, 0x38,
	0x6c, 0xc5, 0x85, 0x7e, 0x99, 0xaf, 0xc0, 0x4e, 0x58, 0xc9, 0xe3, 0x94, 0xe3, 0x8d, 0x1f, 0xd0,
	0x9e, 0x2e, 0xe7, 0xdc, 0xbf, 0x00, 0xbb, 0x39, 0x8c, 0xb8, 0x30, 0xbc, 0x9c, 0x2e, 0x3e, 0xc6,
	0x2b, 0x3a, 0x5d, 0x5c, 0x45, 0xd4, 0x3d, 0x20, 0x0e, 0xd8, 0x61, 0x74, 0x35, 0xbd, 0xbd, 0x5e,
	0xd5, 0xe9, 0xce, 0x68, 0x14, 0xce, 0x57, 0xae, 0xf1, 0x2c, 0x10, 0xeb, 0x1e, 0xa6, 0x76, 0xfe,
	0x33, 0x00, 0x00, 0xff, 0xff, 0x49, 0xc8, 0x4f, 0xc5, 0x9b, 0x04, 0x00, 0x00,
}
